dist: bionic
language: python
python:
  # - 2.7
  - 3.6
  - 3.7
# env:
#   - DJANGO=1.11.13
os: linux
sudo: required

before_install:
  - sudo apt-get update -y
  - sudo apt-get upgrade -y
  - sudo apt-get install -y tidy
  - sudo apt-get install -y swig
  - sudo apt-get install -y graphviz
  - sudo apt-get install -y libreoffice python3-uno
  - libreoffice '--accept=socket,host=localhost,port=8100;urp;' &

install:
  - pip install -U setuptools
  - pip install -U pip
  - pip install coveralls
  - if [[ $TRAVIS_PYTHON_VERSION != 2.7 ]]; then pip install -r requirements.txt; else pip install -r requirements.python3.txt;  fi
#   - test -e "requirements.$TRAVIS_BRANCH.txt" && ( pip install -r "requirements.$TRAVIS_BRANCH.txt" ) || ( pip install -r requirements.txt )
  - pip install -e .
  - pip freeze

script:
  - export LINO_CACHE_ROOT=$TRAVIS_BUILD_DIR/lino_cache
  - mkdir $LINO_CACHE_ROOT
  - inv install
  - inv cov --no-html
#  - inv prep test
#  - python setup.py test

# if [[ $TRAVIS_PYTHON_VERSION == 2* ]]; then inv cov; fi;

after_script:
  - coveralls
